#!/bin/bash
# Replit Setup Script - Copy-paste the commands below into Replit Shell or Secrets

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║           REPLIT SECRETS SETUP - FOLLOW THESE STEPS                   ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "OPTION A: If you have all credentials ready"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. In Replit, go to Secrets (🔒) in the left sidebar"
echo "2. Add each variable below with its value:"
echo ""
echo "REQUIRED:"
echo "├─ NEXTAUTH_SECRET = B1AXW6CUWQHVn5eGTmiA1398Dwa0ueImzuhzRR9s2tc="
echo "├─ NEXTAUTH_URL = https://burch-platform.replit.app"
echo "├─ RESEND_API_KEY = <your key from https://resend.com/api-keys>"
echo "└─ EMAIL_FROM = Burch Platform <onboarding@resend.dev>"
echo ""
echo "PAYMENT (M-Pesa Sandbox - for testing):"
echo "├─ MPESA_ENV = sandbox"
echo "├─ MPESA_CONSUMER_KEY = <from https://developer.safaricom.co.ke>"
echo "├─ MPESA_CONSUMER_SECRET = <from Daraja>"
echo "├─ MPESA_PASSKEY = <from Daraja>"
echo "└─ MPESA_SHORTCODE = 174379"
echo ""
echo "PAYMENT (Flutterwave Test Mode):"
echo "├─ FLUTTERWAVE_SECRET_KEY = <from https://dashboard.flutterwave.com>"
echo "└─ FLUTTERWAVE_SECRET_HASH = <set in Flutterwave webhook config>"
echo ""
echo "OPTIONAL (but recommended):"
echo "├─ ANTHROPIC_API_KEY = <from https://console.anthropic.com>"
echo "├─ GOOGLE_CLIENT_ID = <from Google Cloud Console>"
echo "├─ GOOGLE_CLIENT_SECRET = <from Google Cloud Console>"
echo "└─ EMAIL_OVERRIDE_TO = <your-email@gmail.com>  # Redirect ALL emails for testing"
echo ""
echo ""
echo "OPTION B: Use test/sandbox defaults (easier for initial testing)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "MINIMAL SET (won't have payments/email but app will start):"
echo "├─ NEXTAUTH_SECRET = B1AXW6CUWQHVn5eGTmiA1398Dwa0ueImzuhzRR9s2tc="
echo "└─ NEXTAUTH_URL = https://burch-platform.replit.app"
echo ""
echo ""
echo "OPTION C: Use this file to create a .env.local for LOCAL testing"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If testing locally, create apps/web/.env.local with these values"
echo "(Make sure DATABASE_URL points to local Replit db or external Postgres)"
echo ""
echo ""
echo "After setting Secrets in Replit:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Click RUN button or run in shell:"
echo "   cd apps/web && npm run dev"
echo ""
echo "2. Wait for build to complete (~2-3 min first time)"
echo ""
echo "3. Visit https://burch-platform.replit.app"
echo ""
echo "4. Verify health check:"
echo "   curl https://burch-platform.replit.app/api/health"
echo ""
