import { getServerSession } from "next-auth";
import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { authOptions } from "@/lib/auth";
import { ticketToken } from "@/lib/tickets";
import { qrSvg } from "@/lib/qr";

export const metadata = { title: "Your tickets — dontbeboring" };

/**
 * A ticket carries a live credential, so this page must never be cached or
 * prerendered — a stored copy is a stored key.
 */
export const dynamic = "force-dynamic";

function fmtDate(d: Date) {
  return d.toLocaleDateString("en-KE", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function fmtTime(d: Date) {
  return d.toLocaleTimeString("en-KE", { hour: "2-digit", minute: "2-digit" });
}

export default async function TicketWalletPage({
  params,
}: {
  params: Promise<{ bookingId: string }>;
}) {
  const { bookingId } = await params;

  const session = await getServerSession(authOptions);
  if (!session?.user?.id) redirect("/auth/login");

  const booking = await prisma.booking.findUnique({
    where: { id: bookingId },
    select: {
      id: true,
      userId: true,
      status: true,
      currency: true,
      totalAmount: true,
      event: {
        select: {
          id: true,
          title: true,
          location: true,
          city: true,
          startDate: true,
          partner: { select: { name: true } },
        },
      },
      tickets: {
        orderBy: { serial: "asc" },
        select: { id: true, serial: true, status: true, attendeeName: true, checkedInAt: true },
      },
    },
  });

  if (!booking || !booking.event) notFound();

  // Someone else's booking is a 404, not a 403 — confirming that a booking id
  // exists tells a stranger something they have no business knowing.
  if (booking.userId !== session.user.id) notFound();

  const { event } = booking;

  // Sign every ticket up front so the render below stays synchronous.
  const tickets = await Promise.all(
    booking.tickets.map(async (t) => ({
      ...t,
      svg: t.status === "VALID" ? await qrSvg(ticketToken(t.id), 260) : null,
    }))
  );

  const total = tickets.length;

  // Plenty of registered business names end in a full stop ("Events Co."), and
  // the sentence below adds its own.
  const organiser = event.partner?.name?.replace(/\.\s*$/, "") ?? null;

  return (
    <div className="min-h-screen bg-gray-900 print:bg-white">
      <main className="max-w-2xl mx-auto px-4 py-10 print:py-0">
        <div className="flex items-center justify-between mb-6 print:hidden">
          <Link href="/tickets" className="text-xs font-medium text-orange-300 hover:text-orange-200">
            ← All tickets
          </Link>
          <p className="text-xs text-gray-400">
            {total} ticket{total !== 1 ? "s" : ""}
          </p>
        </div>

        {booking.status !== "CONFIRMED" && (
          <div className="mb-6 rounded-xl border border-amber-400/30 bg-amber-400/10 px-4 py-3 print:hidden">
            <p className="text-sm font-medium text-amber-200">
              This booking is {booking.status.toLowerCase()}.
            </p>
            <p className="text-xs text-amber-200/70 mt-0.5">
              Tickets are only admitted once payment has cleared.
            </p>
          </div>
        )}

        <div className="space-y-6">
          {tickets.map((t) => (
            <article
              key={t.id}
              className="overflow-hidden rounded-2xl bg-white shadow-xl print:shadow-none print:border print:border-gray-200 print:break-inside-avoid"
            >
              {/* ── Stub: the part staff look at ── */}
              <div className="bg-gray-900 px-6 py-5 print:bg-white print:border-b print:border-gray-200">
                <p className="text-[10px] font-semibold tracking-[0.2em] text-orange-300 print:text-orange-700">
                  DONTBEBORING
                </p>
                <h1 className="font-display text-2xl text-white mt-2 leading-tight print:text-gray-900">
                  {event.title}
                </h1>
                <p className="text-sm text-gray-300 mt-2 print:text-gray-600">
                  {fmtDate(event.startDate)} · {fmtTime(event.startDate)}
                </p>
                <p className="text-sm text-gray-400 print:text-gray-600">
                  {event.location}
                  {event.city ? `, ${event.city}` : ""}
                </p>
              </div>

              {/* ── The code ── */}
              <div className="px-6 py-7 flex flex-col items-center">
                {t.svg ? (
                  <>
                    <div
                      className="w-[260px] h-[260px] [&>svg]:w-full [&>svg]:h-full"
                      /* Generated by the QR encoder from a token we produced and
                         charset-validated; it contains no author-supplied markup. */
                      dangerouslySetInnerHTML={{ __html: t.svg }}
                    />
                    <p className="mt-4 text-xs text-gray-400 text-center max-w-xs">
                      Show this at the door. A screenshot works. Each code admits one
                      person, once.
                    </p>
                  </>
                ) : (
                  <div className="w-[260px] h-[260px] rounded-xl bg-gray-50 border border-dashed border-gray-200 flex flex-col items-center justify-center text-center px-6">
                    <p className="text-sm font-semibold text-gray-700">
                      {t.status === "CHECKED_IN" ? "Already used" : "Not valid"}
                    </p>
                    <p className="text-xs text-gray-400 mt-1">
                      {t.status === "CHECKED_IN" && t.checkedInAt
                        ? `Admitted ${fmtDate(t.checkedInAt)} at ${fmtTime(t.checkedInAt)}`
                        : "This ticket was cancelled. Contact the organiser."}
                    </p>
                  </div>
                )}
              </div>

              {/* ── Details ── */}
              <div className="border-t border-gray-100 px-6 py-4 flex items-center justify-between gap-4">
                <div className="min-w-0">
                  <p className="text-[10px] font-semibold tracking-wider text-gray-400">
                    ADMIT
                  </p>
                  <p className="text-sm font-semibold text-gray-900 truncate">
                    {t.attendeeName ?? session.user.name ?? "Guest"}
                  </p>
                </div>
                <div className="text-right flex-shrink-0">
                  <p className="text-[10px] font-semibold tracking-wider text-gray-400">
                    TICKET
                  </p>
                  <p className="text-sm font-semibold text-gray-900">
                    {t.serial} of {total}
                  </p>
                </div>
              </div>

              <div className="bg-gray-50 px-6 py-3 print:bg-white">
                <p className="text-[10px] text-gray-400 leading-relaxed">
                  Issued by dontbeboring
                  {organiser ? ` on behalf of ${organiser}` : ""}. Booking {booking.id}.
                </p>
              </div>
            </article>
          ))}
        </div>

        {tickets.length === 0 && (
          <div className="rounded-2xl bg-white px-6 py-14 text-center">
            <p className="text-sm font-medium text-gray-700">No tickets on this booking yet.</p>
            <p className="text-xs text-gray-400 mt-1">
              Tickets are issued the moment payment clears. If you have paid, give it a
              minute and refresh.
            </p>
          </div>
        )}
      </main>
    </div>
  );
}
